### ISSUE TITLE
Input type=text on IE11

### ISSUE THREAD

**Issue by DekiGk** [ericelliott/h5Validate#103]
When the input field is focused and a user starts typing there is a black X icon appearing on the right part of the input field. Clicking on this the user deletes the text of the input field.

Can this be disabled somehow?

**Comment by ericelliott** [comment]
That black X is not part of h5Validate

**Comment by DekiGk** [comment]
Thanks for the quick reply and sorry for disturbing you with this. It is indeed the IE "setting". For people who want to disable this here is the fix:

http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs
